### ISSUE TITLE
htr_pipeline module not found

### ISSUE THREAD

**Issue by ktoliver** [githubharald/HTRPipeline#1]
Hello! @githubharald 

In both the repo version of `scripts/demo.py` and the code sample that appears in the README file, I'm not able to get the `htr_pipeline` package (`C:\Users\<me>\Git\HTRPipeline\htr_pipeline\__init__.py`) recognized as a module when I run `scripts/demo.py`.

I see this error:

![image](https://user-images.githubusercontent.com/19416435/230130161-8e0e1b1f-8544-433c-a1bc-2155109db8a3.png)

Is there a change I can make to `demo.py` or another file or folder to get past this error? My understanding is that it should work, so I'm not able to troubleshoot.

Thanks!

**Comment by githubharald** [comment]
Hi! Did you install the package as written under README section "Installation" with `pip install .` ?

**Comment by ktoliver** [comment]
> Hi! Did you install the package as written under README section "Installation" with `pip install .` ?

@githubharald Yes, and I didn't pay attention to the output. : p I propose a fix in https://github.com/githubharald/HTRPipeline/pull/2. 

The output of the demo script when I used an added image was rudimentary, as you said. I'll keep looking to see if I can find an OCR model that works with handwriting. I have not found one that works well for my purposes.

**Comment by githubharald** [comment]
Great you figured it out yourself. 
The SimpleHTR model is quite simple (as the name suggests :-D) and also was not trained with a lot of data augmentation, therefore it works for IAM-dataset images, but for other images which look different results are not really good.

You could try to make your input images look more like the IAM-dataset images (high contrast, thick lines, ...). See this [article ](https://towardsdatascience.com/faq-build-a-handwritten-text-recognition-system-using-tensorflow-27648fb18519) section "1.1 Preprocess images".

I wanted to retrain the model with better augmentation but never found the time to do so.

**Comment by githubharald** [comment]
> I have not found one that works well for my purposes.

If you want to share an example feel free to do so. I could add it to my testset and have a look next time that it also works (better).

**Comment by terramaxiver** [comment]
@githubharald 

It might be be best to start with the problem I'm trying to solve (this is a personal project, not work related, so I switched accounts) -- I have thousands of pages of letters written by one person on different colors of paper, some lined, using different colors of ink. I am trying to get the contents of the letters translated to plain text from a doc scan, either as an image file or as a PDF file.

I haven't found a commercial handwritten OCR platform that has come close to identifying even a single word, so I've been applying what little I know about ML and AI to my search. I want to avoid typing all the contents by hand. 

I can think of very laborious ways to do it (maybe training a model by, for example, using image files of different instances of "the" from throughout the pages that are all written by the same person), but I'm not trained in the details of creating a model. I could probably create a basic model to recognize a set of words. Perhaps that is the basis to start with... 

Or should I be able to show a trained model, such as yours, my new data and have it recognize "the" in a line of text written by my letter writer? I tried this, and no words were found, just meaningless text strings associated with some bounding boxes, but not all words on the page had bounding boxes (which means there needs to be more contrast between the background and the text?).

Or, put another way, what steps might I use to solve this problem by using your model?

Thank you!

**Comment by githubharald** [comment]
If you share an example (you can also send me via mail or send a link via linkedin) I can check where things went wrong.
I guess that already the word detection went wrong, and also the CRNN included in this package is quite sensitive to contrast it might be "just" a small image preprocessing needed.

**Comment by terramaxiver** [comment]
@githubharald I sent you a message on LinkedIn. 👍
