### ISSUE TITLE
Trouble Getting Package to work

### ISSUE THREAD

**Issue by andrewredd** [githubharald/HTRPipeline#10]
I'm running the pipeline in the following colab -- https://colab.research.google.com/drive/1AU3Y3wHcG2ys3_yBUzlbsCUMvpVLOV6A?usp=sharing

<img width="1209" alt="image" src="https://github.com/githubharald/HTRPipeline/assets/48295430/948c0126-7630-4ae6-917b-f66f2e402246">

I'm getting many extraneous bounding boxes. I've tried many different configurations including tuning in the web app with little success. 

The output just ends up being garbled -- 
<img width="1029" alt="image" src="https://github.com/githubharald/HTRPipeline/assets/48295430/86482ea7-0a26-49fd-addb-52fd78164f16">

Can I get any tips on how to make this work better? Thanks in advance

**Comment by githubharald** [comment]
can you provide the raw image file please (as a png file)?
the model is trained on the IAM dataset, so do not expect the model to perfectly generalize to every handwritten font.
