### ISSUE TITLE
train the model on my dataset

### ISSUE THREAD

**Issue by heba1518** [githubharald/HTRPipeline#11]
Hi, thank you so much for this helpful repo,
I want your help to train this model on my dataset, can you tell me what should I do?

**Comment by githubharald** [comment]
I kept the training code for this repo closed source. The closest you can get it to use SimpleHTR instead, there, the training code is included.

**Comment by heba1518** [comment]
ok, I will do, thanks

**Comment by anurshetyy** [comment]
[Uploading line-model.zip…]()
