### ISSUE TITLE
pkg_resources not found issue

### ISSUE THREAD

**Issue by gangsta-techie** [githubharald/HTRPipeline#12]
ModuleNotFoundError: No module named 'pkg_resources'. 
Im facing this issue while trying to run on my local system. Followed the steps given. What to do?

**Comment by gangsta-techie** [comment]
![Screenshot 2024-03-03 200444](https://github.com/githubharald/HTRPipeline/assets/119859686/25594bf7-20e1-4ffe-8cbf-15b70a15ec7a)

**Comment by githubharald** [comment]
try to install setuptools

**Comment by ks27082002** [comment]
i did pip install . at root again but still gives same result

**Comment by gangsta-techie** [comment]
where can i get more info about the models used, their training technique and data on which they are trained?
btw, highly appreciate your work!!!

**Comment by githubharald** [comment]
detector: https://github.com/githubharald/WordDetectorNN
reader: not open source, but it's a CRNN architecture, and the closest you can find is this one https://github.com/githubharald/SimpleHTR

you might also want to read https://towardsdatascience.com/2326a3487cd5 for some details on the CRNN, and this one https://githubharald.github.io/word_detector.html about the detector.

**Comment by gangsta-techie** [comment]
thank you so much, btw where can i connect with you for any further queries?
