### ISSUE TITLE
Failing while using test data

### ISSUE THREAD

**Issue by himanshudwd765** [githubharald/HTRPipeline#14]
I'm a beginner in ML field, I followed the steps and successfully ran the model, but it fails on simple test data. Could I be missing something?

![Screenshot 2024-07-04 at 3 52 05 PM](https://github.com/githubharald/HTRPipeline/assets/16178794/ac45dbd8-fa67-48ca-ad28-9186a20c000e)

**Comment by githubharald** [comment]
it is due to the word detector part, the model is not trained to detect such big words (most likely the image has a high resolution).
try either the scale parameter (first slider in the web UI), or try manually downscaling the image.

**Comment by its-shrivatsavan** [comment]
Does the model recognize symbols?

**Comment by githubharald** [comment]
in the file reader.json (which you get when you download the model) you see the list of all characters that the model can read
