### ISSUE TITLE
can't dl models

### ISSUE THREAD

**Issue by pinballelectronica** [githubharald/HTRPipeline#5]
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/githubharald/HTRPipeline.git/info/lfs'

**Comment by githubharald** [comment]
Thanks for pointing this out. I will put the model on dropbox instead.

**Comment by pinballelectronica** [comment]
Thank you.  Very excited to use this! :)

**Comment by pinballelectronica** [comment]
Do you have an ETA or could you tell me the names of the models and i'll go hunting on HF or wherever for them?  Thank you.

**Comment by githubharald** [comment]
Will change the repo in the next days. You can use those model weights, put them in the stored_model folders (detector, reader) and only then install the package.
https://www.dropbox.com/s/1rq3p1tyaeoeg4l/HTRPipeline.zip?dl=0

**Comment by pinballelectronica** [comment]
Very kind, thank you.

**Comment by githubharald** [comment]
updated repo, weights now have to be downloaded via dropbox as github lfs runs out of bandwidth too soon.
