### ISSUE TITLE
Model not recognizing my handwritting

### ISSUE THREAD

**Issue by Emmybritt** [githubharald/HTRPipeline#7]
Hi... i setup this project on my local machine, and i t worked fine, so i decided to try it with my handwriting, so i wrote on a paper and tried the model out to print out the text from my handwriting paper, but it return some  gibberish text like this, i tried it with several other handwritten  paper i snapped with my phone and sent to my pc.. here is an example of result i was getting.`A - I A H A A I S I IS AE A IN A WT W I I A A I A A AD IN N A IN IS A A A I A WS I A R OR I IT A I A A I I I A M`.

 I  wanted to ask if there are any ways i can improve the model and put in my own datasets to train the model to suite my taste, and also if it is also possible to get other once that i can try out.
 and here are some handwriting papers i used 
![IMG-20230711-WA0010](https://github.com/githubharald/HTRPipeline/assets/86298566/63af067d-e2d2-4158-9936-fb6718be90d0)
![IMG-20230711-WA0011](https://github.com/githubharald/HTRPipeline/assets/86298566/fded19fa-1202-412b-b5c2-abacc7402057)
![IMG_20230714_174640](https://github.com/githubharald/HTRPipeline/assets/86298566/86dc62ac-f14f-4057-96c6-0322650bb88a)
 
![1689429079039](https://github.com/githubharald/HTRPipeline/assets/86298566/a5cd72e6-1ab9-488f-93a9-24e076d1d3ec)
![IMG_20230706_093603](https://github.com/githubharald/HTRPipeline/assets/86298566/25a31223-b9e4-4bfe-9246-6f2ebf13b5ac)

![27cbd85b18d43a966e82b013ec9d126c](https://github.com/githubharald/HTRPipeline/assets/86298566/3445acd0-abfd-441a-ba54-4d63f2728b9a)
![1689354215206](https://github.com/githubharald/HTRPipeline/assets/86298566/cdb0e1c6-c2af-40bb-87cc-5b731c79bbe4)

**Comment by githubharald** [comment]
Hi, as written in the README the height of the text in the resized image must be roughly 50px to get good results. If I take your image "253744064-a5cd72e6-1ab9-488f-93a9-24e076d1d3ec.jpg" and resize it to 200px then the text in the resized image is roughly 50px, and then results are not that bad (but also not perfect).


![grafik](https://github.com/githubharald/HTRPipeline/assets/15148095/1f84d828-558b-493b-ab16-28779a312945)
